export const navLink=[
    {
        link:'/',
        text:'navbar.home'
    },
    {
        link:'/room',
        text:'navbar.rooms'
    },
    {
        link:'/about',
        text:'navbar.about'
    },
    {
        link:'/gallery',
        text:'navbar.gallery'
    },
    {
        link:'/news',
        text:'navbar.news'
    },
    {
        link:'/contact',
        text:'navbar.contact'
    }
]